services:
  clock:
    image: ghcr.io/bferg314/clock:latest
    container_name: clock
    restart: unless-stopped
    ports:
      - "8080:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
